import { type Lang } from '../data/framework';
import { useAuth } from '../context/AuthContext';
import PersistentBusinessWorkspace, { BusinessField as Field } from './PersistentBusinessWorkspace';
import { PERSPECTIVES, type StrategyInput, type StrategyObjective, type StrategyInitiative, type StrategyKpi, type strategyMetrics } from '../services/strategyExcellenceWorkspace';
const nextCode=(prefix:string,items:{Code:string}[])=>{let n=1;while(items.some(i=>i.Code===prefix+n))n++;return prefix+n;};
const numeric=(v:string)=>v===''?null:Number(v);
const action='rounded-lg border b-line-soft px-2 py-1.5 text-xs tx2 disabled:opacity-40';
export default function StrategyWorkspace({lang,projectId}:{lang:Lang;projectId:string}) {
  const {user}=useAuth(),fa=lang==='fa',t=(a:string,b:string)=>fa?a:b;
  return <PersistentBusinessWorkspace<StrategyInput,ReturnType<typeof strategyMetrics>> key={`${projectId}:${user?.id}`} lang={lang} projectId={projectId} userId={user?.id??null} path="spm" resource="plans"
    title={t('استراتژی — برنامه‌های ذخیره‌شده','Strategy — persisted plans')}
    notice={t('BSC داخلی: چهار منظر با وزن ۳۰/۲۵/۲۵/۲۰. تحقق، پیشرفت از مبنا به هدف با سقف ۱۰۰٪ است؛ دادهٔ واقعیِ نامعلوم، صفر نیست. ارقام ابتکارات اظهار دستی‌اند، نه دفتر هزینهٔ مالی.','Internal BSC: four perspectives weighted 30/25/25/20. Attainment is baseline-to-target progress capped at 100%; missing observations are not zero. Initiative costs are manually declared, not the finance ledger.')}
    newValue={()=>({Code:'',TitleFa:'',DataDate:new Date().toISOString().slice(0,10),Objectives:[],Initiatives:[]})}
    editor={(v,set)=><StrategyEditor value={v} set={set} lang={lang}/>}
    result={row=>{
      const fmt=(n:number|null)=>n===null?'—':n.toLocaleString(fa?'fa-IR':'en-US',{maximumFractionDigits:2});
      const pct=(n:number|null)=>n===null?'—':fmt(n*100)+'%';
      return <>
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-2">{[[t('تحقق کل','Overall attainment'),pct(row.metrics.attainment)],[t('اهداف زیر ۹۰٪','Objectives below 90%'),fmt(row.metrics.offTrack)],[t('اهداف با دادهٔ ناقص','Objectives with missing data'),fmt(row.metrics.unknownObjectives)],[t('ابتکارات فعال','Active initiatives'),fmt(row.metrics.activeInitiatives)]].map(([label,value])=><div key={label} className="rounded-lg border b-line-soft p-3"><p className="text-xs tx3">{label}</p><p className="text-xl tx1">{value}</p></div>)}</div>
        <p className="text-xs tx3">{t('تحقق کل تنها با دادهٔ کامل هر چهار منظر محاسبه می‌شود. وزن اهداف و شاخص‌ها در گروه خود نرمال می‌شود.','Overall attainment requires complete data in all four perspectives. Objective and KPI weights are normalized within their group.')}</p>
        <div className="grid sm:grid-cols-4 gap-2">{row.metrics.perspectives.map(m=><div key={m.code} className="border b-line-soft rounded-lg p-2 text-xs tx2">{PERSPECTIVES.find(p=>p.code===m.code)?.label[lang]} · {m.weight}%<strong className="block tx1 mt-2">{pct(m.attainment)}</strong></div>)}</div>
        {row.Objectives.map((o,idx)=><section key={o.Code} className="border b-line-soft rounded-xl p-3 space-y-2"><h4 className="text-sm tx1">{o.Code} · {o.TitleFa} — {pct(row.metrics.objectives[idx].attainment)}</h4><div className="overflow-x-auto"><table className="w-full text-xs tx2"><thead><tr>{[t('شاخص','KPI'),t('واحد','Unit'),t('مبنا','Baseline'),t('هدف','Target'),t('واقعی','Actual'),t('وزن','Weight'),t('تحقق','Attainment')].map(s=><th key={s} className="p-2 text-start">{s}</th>)}</tr></thead><tbody>{o.Kpis.map((k,n)=><tr key={k.Code}><td className="p-2">{k.Code} · {k.TitleFa}</td><td>{k.Unit}</td><td>{fmt(k.Baseline)}</td><td>{fmt(k.Target)}</td><td>{fmt(k.Actual)}</td><td>{fmt(k.Weight)}</td><td>{pct(row.metrics.objectives[idx].kpis[n].attainment)}</td></tr>)}</tbody></table></div></section>)}
        {row.Initiatives.map(i=><article key={i.Code} className="border b-line-soft rounded-xl p-3 text-xs tx2 space-y-1"><h4 className="tx1">{i.Code} · {i.TitleFa}</h4><p>{i.ObjectiveCodes.join(' / ')} · {i.Status} · {t('پیشرفت','Progress')}: {i.Progress===null?'—':fmt(i.Progress)+'%'}</p><p>{t('بودجه / هزینه','Budget / spent')}: {fmt(i.Budget)} / {fmt(i.Spent)} {i.Currency}</p></article>)}
        {row.metrics.currencies.map(c=><p key={c.currency} className="text-xs tx3">{c.currency} · {t('جمع بودجه / هزینه / مصرف','Total budget / spent / utilisation')}: {fmt(c.budget)} / {fmt(c.spent)} / {pct(c.utilisation)}</p>)}
      </>;
    }}/>;
}
function StrategyEditor({value:v,set,lang}:{value:StrategyInput;set:(v:StrategyInput)=>void;lang:Lang}) {
  const t=(a:string,b:string)=>lang==='fa'?a:b;
  const objective=(index:number,patch:Partial<StrategyObjective>)=>{
    const previous=v.Objectives[index].Code;
    set({...v,Objectives:v.Objectives.map((o,n)=>n===index?{...o,...patch}:o),Initiatives:patch.Code!==undefined?v.Initiatives.map(i=>({...i,ObjectiveCodes:i.ObjectiveCodes.map(c=>c===previous?patch.Code!:c)})):v.Initiatives});
  };
  const kpi=(oi:number,ki:number,patch:Partial<StrategyKpi>)=>objective(oi,{Kpis:v.Objectives[oi].Kpis.map((k,n)=>n===ki?{...k,...patch}:k)});
  const initiative=(index:number,patch:Partial<StrategyInitiative>)=>set({...v,Initiatives:v.Initiatives.map((i,n)=>n===index?{...i,...patch}:i)});
  return <div className="space-y-3">
    <h4 className="text-sm tx1">{t('اهداف و شاخص‌ها','Objectives and KPIs')}</h4>
    {v.Objectives.map((o,oi)=><section key={oi} className="rounded-xl border b-line-soft p-3 space-y-3">
      <div className="grid sm:grid-cols-4 gap-2"><Field label={t('کد هدف','Objective code')} value={o.Code} onChange={s=>objective(oi,{Code:s})}/><Field label={t('عنوان هدف','Objective title')} value={o.TitleFa} onChange={s=>objective(oi,{TitleFa:s})}/><label className="text-xs tx3">{t('منظر','Perspective')}<select className="block w-full rounded-lg border b-line-soft bg-[var(--row)] mt-1 p-2 tx1" value={o.Perspective} onChange={e=>objective(oi,{Perspective:e.target.value})}>{PERSPECTIVES.map(p=><option key={p.code} value={p.code}>{p.label[lang]}</option>)}</select></label><Field label={t('وزن هدف','Objective weight')} type="number" min={.001} max={100} value={o.Weight} onChange={s=>objective(oi,{Weight:numeric(s)!})}/></div>
      {o.Kpis.map((k,ki)=><div key={ki} className="rounded-lg bg-[var(--row)] p-2 space-y-2"><div className="grid sm:grid-cols-3 xl:grid-cols-5 gap-2">
        <Field label={t('کد شاخص','KPI code')} value={k.Code} onChange={s=>kpi(oi,ki,{Code:s})}/><Field label={t('نام شاخص','KPI title')} value={k.TitleFa} onChange={s=>kpi(oi,ki,{TitleFa:s})}/><Field label={t('واحد','Unit')} value={k.Unit} onChange={s=>kpi(oi,ki,{Unit:s})}/>
        <Field label={t('مبنا','Baseline')} type="number" value={k.Baseline} onChange={s=>kpi(oi,ki,{Baseline:numeric(s)!})}/><Field label={t('هدف','Target')} type="number" value={k.Target} onChange={s=>kpi(oi,ki,{Target:numeric(s)!})}/><Field label={t('واقعی — خالی یعنی نامعلوم','Actual — blank means unknown')} type="number" optional value={k.Actual} onChange={s=>kpi(oi,ki,{Actual:numeric(s)})}/><Field label={t('وزن شاخص','KPI weight')} type="number" min={.001} max={100} value={k.Weight} onChange={s=>kpi(oi,ki,{Weight:numeric(s)!})}/>
        <label className="text-xs tx3">{t('جهت','Direction')}<select className="block w-full rounded-lg border b-line-soft bg-[var(--row)] mt-1 p-2 tx1" value={k.Direction} onChange={e=>kpi(oi,ki,{Direction:e.target.value as 'up'|'down'})}><option value="up">{t('افزایش بهتر است','Higher is better')}</option><option value="down">{t('کاهش بهتر است','Lower is better')}</option></select></label>
      </div><button type="button" className={action} onClick={()=>objective(oi,{Kpis:o.Kpis.filter((_,n)=>n!==ki)})}>{t('حذف شاخص از پیش‌نویس','Remove draft KPI')}</button></div>)}
      <div className="flex flex-wrap gap-2"><button type="button" className={action} disabled={o.Kpis.length>=20} onClick={()=>objective(oi,{Kpis:[...o.Kpis,{Code:nextCode('K',o.Kpis),TitleFa:'',Unit:'',Baseline:0,Target:100,Actual:null,Direction:'up',Weight:1}]})}>{t('افزودن شاخص','Add KPI')}</button><button type="button" className={action} disabled={v.Initiatives.some(i=>i.ObjectiveCodes.includes(o.Code))} onClick={()=>set({...v,Objectives:v.Objectives.filter((_,n)=>n!==oi)})}>{t('حذف هدف — فقط بدون پیوند ابتکار','Remove objective — only when unlinked')}</button></div>
    </section>)}
    <button type="button" className={action} disabled={v.Objectives.length>=30} onClick={()=>set({...v,Objectives:[...v.Objectives,{Code:nextCode('O',v.Objectives),TitleFa:'',Perspective:'financial',Weight:1,Kpis:[]}]})}>{t('افزودن هدف','Add objective')}</button>
    <h4 className="text-sm tx1">{t('ابتکارات — ارقام اظهارشده','Initiatives — declared figures')}</h4>
    {v.Initiatives.map((i,idx)=><section key={idx} className="rounded-xl border b-line-soft p-3 space-y-2"><div className="grid sm:grid-cols-3 gap-2"><Field label={t('کد ابتکار','Initiative code')} value={i.Code} onChange={s=>initiative(idx,{Code:s})}/><Field label={t('عنوان','Title')} value={i.TitleFa} onChange={s=>initiative(idx,{TitleFa:s})}/><Field label={t('پیشرفت — اختیاری','Progress — optional')} type="number" min={0} max={100} optional value={i.Progress} onChange={s=>initiative(idx,{Progress:numeric(s)})}/><Field label={t('بودجه — اختیاری','Budget — optional')} type="number" min={0} optional value={i.Budget} onChange={s=>initiative(idx,{Budget:numeric(s)})}/><Field label={t('هزینه — اختیاری','Spent — optional')} type="number" min={0} optional value={i.Spent} onChange={s=>initiative(idx,{Spent:numeric(s)})}/><Field label={t('ارز (IRR / USD / …)','Currency (IRR / USD / …)')} value={i.Currency} onChange={s=>initiative(idx,{Currency:s.toUpperCase()})}/><label className="text-xs tx3">{t('وضعیت اظهارشده','Declared status')}<select className="block w-full rounded-lg border b-line-soft bg-[var(--row)] mt-1 p-2 tx1" value={i.Status} onChange={e=>initiative(idx,{Status:e.target.value as StrategyInitiative['Status']})}>{(['on_track','at_risk','delayed','completed'] as const).map(s=><option key={s} value={s}>{s}</option>)}</select></label></div>
      <div className="flex flex-wrap gap-3 text-xs tx2">{t('اهداف پشتیبانی‌شده:','Supports objectives:')}{v.Objectives.map(o=><label key={o.Code}><input type="checkbox" checked={i.ObjectiveCodes.includes(o.Code)} onChange={e=>initiative(idx,{ObjectiveCodes:e.target.checked?[...i.ObjectiveCodes,o.Code]:i.ObjectiveCodes.filter(c=>c!==o.Code)})}/> {o.Code} · {o.TitleFa}</label>)}</div>
      <button type="button" className={action} onClick={()=>set({...v,Initiatives:v.Initiatives.filter((_,n)=>n!==idx)})}>{t('حذف ابتکار از پیش‌نویس','Remove draft initiative')}</button>
    </section>)}
    <button type="button" className={action} disabled={!v.Objectives.length||v.Initiatives.length>=100} onClick={()=>set({...v,Initiatives:[...v.Initiatives,{Code:nextCode('I',v.Initiatives),TitleFa:'',ObjectiveCodes:[v.Objectives[0].Code],Progress:null,Budget:null,Spent:null,Currency:'IRR',Status:'on_track'}]})}>{t('افزودن ابتکار','Add initiative')}</button>
  </div>;
}
